---
---

<center> <h1>üìç üìç Assignment: Reading Files üìç üìç</h1> </center>

---

#### `1. READ THE BIG MART SALES DATA`

---

In [2]:
import pandas as pd

In [8]:
data = pd.read_csv('dataset/big_mart_sales.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/big_mart_sales.csv'

---

***So, we are getting an error. You task is to find out the error and read the file using pandas. Here is the screenshot of the CSV file.***

![](images/csv.png)

---

In [18]:
### WRITE YOUR CODE HERE
#The Error is due to the fact that the directory is wrong and also the first 5 five rows are not in the right format for Pandas to read.

data = pd.read_csv('C:/Users/palanil/Downloads/assignment_ds_1-200323-120502/1/dataset/big_mart_sales.csv',skiprows=5)
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [19]:
data.loc[2:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
2,FDN15,17.500,Low Fat,0.01676,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.00000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.00000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.00000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

----

####  `2. READ THE JSON DATA`

----

In [20]:
# read the json file
json_data = pd.read_json('dataset/simple.json')

ValueError: Expected object or value

---

***Open the JSON file in the text editor and see what can you do to read the file.***

---

In [7]:
#### WRITE YOUR CODE HERE

In [23]:
json_data = pd.read_json('C:/Users/palanil/Downloads/assignment_ds_1-200323-120502/1/dataset/simple.json',lines = True)

json_data.head()

      name  age grade
0    Andew   12     A
1   Bhuvan   18     B
2  Clinton   11     A
3    Drake   12     C
4    Eisha   13     B